### ISSUE TITLE
Can not install dependencies in all notebooks.

### ISSUE THREAD

**Issue by noumanistic** [pablo-arantes/making-it-rain#93]
downloading dependencies is giving error. 
if one is fixed by any chance another appears.

**Comment by pablo-arantes** [comment]
Can you please be more specific? Which notebook are you having errors? And are you using the last version available in the Making it Rain site?

**Comment by noumanistic** [comment]
I am using this notebook.
https://colab.research.google.com/github/pablo-arantes/making-it-rain/blob/main/Protein_ligand.ipynb
while installing dependencies it gives error about pytraj first. when i
install it separate code, it then gives error about openmm.
please have a look on it so you will also see there are number of errors.
[image: image.png]
[image: image.png]

**Comment by noumanistic** [comment]
![openmm error](https://github.com/pablo-arantes/making-it-rain/assets/124342843/fdc86198-3a94-4f6c-85d5-b6c78022148b)

**Comment by ysa123-2** [comment]
I meet some problem
![Presentation1](https://github.com/pablo-arantes/making-it-rain/assets/153471649/e1a6514f-5cf0-481b-a0d9-e4f1cc122db4)

**Comment by zjun028** [comment]
Same problem

**Comment by andrewsb8** [comment]
I'm coming across this as well. It appears to be an issue with conda and the cudatoolkit package:

```
!mamba install openmm -c conda-forge -y
```

```
Looking for: ['openmm']

conda-forge/linux-64                                        Using cache
conda-forge/noarch                                          Using cache
No package can be installed for pin: cudatoolkit 12.2.*

# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "/usr/local/lib/python3.10/site-packages/conda/exceptions.py", line 1124, in __call__
        return func(*args, **kwargs)
      File "/usr/local/lib/python3.10/site-packages/mamba/mamba.py", line 941, in exception_converter
        raise e
      File "/usr/local/lib/python3.10/site-packages/mamba/mamba.py", line 934, in exception_converter
        exit_code = _wrapped_main(*args, **kwargs)
      File "/usr/local/lib/python3.10/site-packages/mamba/mamba.py", line 892, in _wrapped_main
        result = do_call(parsed_args, p)
      File "/usr/local/lib/python3.10/site-packages/mamba/mamba.py", line 754, in do_call
        exit_code = install(args, parser, "install")
      File "/usr/local/lib/python3.10/site-packages/mamba/mamba.py", line 547, in install
        solver.add_pin(final_spec)
    RuntimeError: No package can be installed for pin: cudatoolkit 12.2.*

`$ /usr/local/bin/mamba install openmm -c conda-forge -y`

  environment variables:
                 CIO_TEST=<not set>
COLAB_DEBUG_ADAPTER_MUX_PATH=/usr/local/bin/dap_multiplexer
COLAB_LANGUAGE_SERVER_PROXY=<set>
               CONDA_ROOT=/usr/local
           CURL_CA_BUNDLE=<not set>
          LD_LIBRARY_PATH=/usr/local/lib:/usr/local/nvidia/lib:/usr/local/nvidia/lib64
               LD_PRELOAD=<not set>
             LIBRARY_PATH=/usr/local/cuda/lib64/stubs
                     PATH=/opt/bin:/usr/local/nvidia/bin:/usr/local/cuda/bin:/usr/local/sbin:/us
                          r/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/tools/node/bin:/tools/googl
                          e-cloud-sdk/bin
               PYTHONPATH=/env/python
           PYTHONWARNINGS=ignore:::pip._internal.cli.base_command
       REQUESTS_CA_BUNDLE=<not set>
            SSL_CERT_FILE=<not set>
               TCLLIBPATH=/usr/share/tcltk/tcllib1.20

     active environment : None
       user config file : /root/.condarc
 populated config files : /usr/local/.condarc
          conda version : 23.1.0
    conda-build version : not installed
         python version : 3.10.10.final.0
       virtual packages : __archspec=1=x86_64
                          __glibc=2.35=0
                          __linux=6.1.58=0
                          __unix=0=0
       base environment : /usr/local  (writable)
      conda av data dir : /usr/local/etc/conda
  conda av metadata url : None
           channel URLs : https://conda.anaconda.org/conda-forge/linux-64
                          https://conda.anaconda.org/conda-forge/noarch
          package cache : /usr/local/pkgs
                          /root/.conda/pkgs
       envs directories : /usr/local/envs
                          /root/.conda/envs
               platform : linux-64
             user-agent : conda/23.1.0 requests/2.28.2 CPython/3.10.10 Linux/6.1.58+ ubuntu/22.04.3 glibc/2.35
                UID:GID : 0:0
             netrc file : None
           offline mode : False


An unexpected error has occurred. Conda has prepared the above report.
```

The same problem prevents `!mamba install -c conda-forge gcc=12.1.0 -y` and manual install commands like `!mamba install -c conda-forge cudatoolkit=12.1 -y` do not change the outcome. The "pin" to cudatoolkit=12.2.* persists.

**Comment by pablo-arantes** [comment]
Hi All,

I've corrected all the notebooks, and everything should be functioning properly now. Please try again and let me know if you encounter any issues.

Thank you.

Pablo
